name: Simon Inc
favicon: null
layout_spectrum: 0.25304
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.10380497085861862
  lightness: 0.7731863625813276
  saturation: 0.3123734830878675
  rhythmicContrast: 0.01866275235079229
purpose: []
